name: Aaraam
description: Courier Delivery App.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0-0
  carousel_slider: ^4.0.0-nullsafety.0
  webview_flutter: ^2.0.4
  form_field_validator: ^1.0.1
  plugin_platform_interface: ^2.0.0
  http: any
  shared_preferences: any
  firebase_core: ^1.1.1
  firebase_messaging: ^9.1.4
  overlay_support: ^1.2.1
  url_launcher: ^6.0.3
  share: ^2.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/facebook.jpg
    - assets/images/google.jpg
    - assets/images/onboarding_1.png
    - assets/images/main_top.png
    - assets/images/main_bottom.png
    - assets/images/delivery_3.png
    - assets/images/login_bottom.png
    - assets/images/icon1.png
    - assets/images/icon2.png
    - assets/images/icon3.png
    - assets/images/contact.png
    - assets/images/contactus.png
    - assets/images/delivery.png
    - assets/images/email.png
    - assets/images/location.png
    - assets/images/telephone.png
    - assets/images/book.jpg
    - assets/images/rocket.png
    - assets/images/chat.png
    - assets/images/booking.png
    - assets/images/pricing.png
    - assets/images/one.png
    - assets/images/noorder.png

  fonts:
        - family: Roboto
          fonts:
            - asset: assets/fonts/Roboto-Medium.ttf

        - family: OpenSans
          fonts:
            - asset: assets/fonts/OpenSans.ttf




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
